import { describe, expect, it } from "vitest";
import { ContextTracker, estimateCost, estimateTokens } from "../src/audit/metrics.js";
import { compactExecOutput, compactOldToolResults, compactRagOverlap, selectHistory } from "../src/audit/optimizations.js";
import { EXEC_TOOL } from "../src/agent/tools/exec.js";

describe("token audit estimates and optimizations", () => {
  it("calculates truthful cost with cached input excluded from uncached input", () => expect(estimateCost({ inputTokens: 100, outputTokens: 20, cachedTokens: 40, reasoningTokens: 5 }, { inputUsdPer1M: 2, cachedInputUsdPer1M: 1, outputUsdPer1M: 3, reasoningUsdPer1M: 4 })).toBe((60 * 2 + 40 + 20 * 3 + 5 * 4) / 1_000_000));
  it("uses zero cost when exact provider usage is unavailable", () => expect(estimateCost(null, { inputUsdPer1M: 2, cachedInputUsdPer1M: 1, outputUsdPer1M: 3, reasoningUsdPer1M: 4 })).toBe(0));
  it("classifies context and detects only later-call repetition", () => { const tracker = new ContextTracker(); const messages = [{ category: "system" as const, message: { role: "system" as const, content: "rules" } }, { category: "user" as const, message: { role: "user" as const, content: "question" } }]; const first = tracker.measure(messages, [EXEC_TOOL]); const second = tracker.measure(messages, [EXEC_TOOL]); expect(first.repeatedInputTokensEstimated).toBe(0); expect(second.repeatedInputTokensEstimated).toBe(first.newInputTokensEstimated); expect(first.systemTokensEstimated).toBeGreaterThan(0); expect(first.userTokensEstimated).toBeGreaterThan(0); expect(first.toolsTokensEstimated).toBeGreaterThan(0); });
  it("keeps chronological complete exchanges and skips oversized exchanges without bypassing the budget", () => { const history = [{ role: "user" as const, content: "old" }, { role: "assistant" as const, content: "old answer" }, { role: "user" as const, content: "new" }, { role: "assistant" as const, content: "x".repeat(100) }]; const newestCost = estimateTokens(history[2]) + estimateTokens(history[3]); expect(selectHistory(history, newestCost)).toEqual(history.slice(2)); expect(selectHistory(history, 1)).toEqual([]); });
  it("compacts exec output with prefix, suffix, status, and original sizes", () => { const original = JSON.stringify({ ok: false, exitCode: 9, timedOut: true, truncated: false, stdout: `PREFIX${"x".repeat(500)}SUFFIX`, stderr: "error" }); const result = compactExecOutput(original, 220); const parsed = JSON.parse(result.content); expect(result.compacted).toBe(true); expect(parsed.ok).toBe(false); expect(parsed.exitCode).toBe(9); expect(parsed.timedOut).toBe(true); expect(parsed.stdout).toContain("PREFIX"); expect(parsed.stdout).toContain("SUFFIX"); expect(parsed.originalChars).toBe(original.length); expect(parsed.originalBytes).toBe(Buffer.byteLength(original)); });
  it("retains the newest tool round while replacing older results with receipts", () => { const messages = [{ role: "user" as const, content: "q" }, { role: "assistant" as const, content: "", toolCalls: [{ id: "a", name: "exec", arguments: {} }] }, { role: "tool" as const, toolCallId: "a", content: JSON.stringify({ ok: true, stdout: "repeatable evidence ".repeat(40) }) }, { role: "assistant" as const, content: "", toolCalls: [{ id: "b", name: "search_documents", arguments: {} }] }, { role: "tool" as const, toolCallId: "b", content: JSON.stringify({ status: "ok", results: [{ text: "repeatable evidence ".repeat(40) + "new evidence" }] }) }]; const compacted = compactOldToolResults(messages); expect(compacted[2]!.content).not.toContain("private old output"); expect(compacted[2]!.content).toContain("full output seen previously"); expect(compacted[4]).toEqual(messages[4]); });
  it("removes only exact adjacent same-source RAG overlap and keeps the top result complete", () => { const overlap = "exact overlap ".repeat(30); const topText = "alpha " + overlap; const content = JSON.stringify({ status: "ok", results: [{ text: topText, filename: "a.txt", chunkIndex: 0, distance: 0.1 }, { text: overlap + " beta", filename: "a.txt", chunkIndex: 1, distance: 0.2 }, { text: "exact overlap gamma", filename: "b.txt", chunkIndex: 2, distance: 0.3 }] }); const compacted = compactRagOverlap(content); const results = JSON.parse(compacted.content).results; expect(results[0].text).toBe(topText); expect(results[1].text).toContain("overlap omitted"); expect(results[1].text).toContain(" beta"); expect(results[2].text).toBe("exact overlap gamma"); });
  it("does not delete merely similar adjacent text", () => { const content = JSON.stringify({ status: "ok", results: [{ text: "colour", filename: "a.txt", chunkIndex: 0 }, { text: "color", filename: "a.txt", chunkIndex: 1 }] }); expect(compactRagOverlap(content)).toEqual({ content, compacted: false }); });
  it("does not remove exact text from non-adjacent chunks without page metadata", () => { const content = JSON.stringify({ status: "ok", results: [{ text: "alpha overlap", filename: "a.txt", chunkIndex: 0 }, { text: "overlap beta", filename: "a.txt", chunkIndex: 3 }] }); expect(compactRagOverlap(content)).toEqual({ content, compacted: false }); });
});
